SELECT FLAVOR
FROM (
    SELECT H.FLAVOR AS FLAVOR, COALESCE(H.TOTAL_ORDER, 0) + COALESCE(J.TOTAL_ORDER, 0) AS TOTAL
    FROM FIRST_HALF H
    LEFT JOIN JULY J
    ON H.FLAVOR = J.FLAVOR
    
    UNION
    
    SELECT H.FLAVOR AS FLAVOR, COALESCE(H.TOTAL_ORDER, 0) + COALESCE(J.TOTAL_ORDER, 0) AS TOTAL
    FROM JULY J
    LEFT JOIN FIRST_HALF H
    ON H.FLAVOR = J.FLAVOR
) AS COMBINED
GROUP BY FLAVOR
ORDER BY SUM(TOTAL) DESC
LIMIT 3;